# Documentation: http://docs.travis-ci.com/user/languages/julia/
sudo: required
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
notifications:
  email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
script:
  - sudo ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("SpikeSorting"); Pkg.test("SpikeSorting"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SpikeSorting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
