environment:
  matrix:
  - julia_version: 1.0
  - julia_version: 1.3

platform:
  - x64

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
    # Download most recent Julia Windows binary
    - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"SpikeSorting\"); Pkg.build(\"SpikeSorting\")"

test_script:
  - C:\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"SpikeSorting\")"
