name = "SpikeSorting"
uuid = "acc641c0-d14d-5ed3-8a01-2b4adfca2b15"
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"

[compat]
Interpolations = "x.y.z"
DistributedArrays = "x.y.z"
Gtk = "x.y.z"
Cairo = "x.y.z"
MultivariateStats = "x.y.z"
julia = "1.3"
